### ISSUE TITLE
Taller de flutter

### ISSUE THREAD

**Issue by Danieltache17** [ISCOUTB/DH-VocesdelAula#1]
Aprendiendo flutter . . . 🤔
Entorno de desarrollo

**Comment by extremeblack1** [comment]
Tengo hambre, pero aprendiendo Flutter :3

**Comment by Danieltache17** [comment]
**Daniel Alejandro Tache Lara - T00069214**

Aprendiendo flutter . . . 🤔

El día de ayer 3 de septiembre instale flutter, el sdk de dart, android studio, visual studio y visual studio code luego de eso añadi los sdk de dart y flutter a las variables de entorno del sistema, con eso ultimo deje listo mi entorno de desarrollo en visual studio code con el codigo que nos da flutter predeterminado, hice la prueba con un emulador de telefono android en android studio tambien hice la prueba en la web e hice un simple codido de una calculadora apoyandome en youtube a manera de practica con el fin de familiarisarme con el lenguaje de programacion dart.

**Comment by leogoca00** [comment]
Empezando con Flutter . . . 

Desde el dia 1 de septiembre, instalé Flutter, el SDK de Dart y  Android Studio (Visual Studio y Visual Studio Code no prorque ya lo tenia instalado :D). Posteriormente, añadí los SDK de Dart y Flutter a las variables de entorno del sistema. Con esto, configuré mi entorno de desarrollo en Visual Studio Code utilizando el código predeterminado que ofrece Flutter. Realicé pruebas con un emulador de teléfono Android en Android Studio y también verifiqué en la web. Para poner en práctica mis conocimientos, creé una simple calculadora siguiendo tutoriales en YouTube, con el objetivo de familiarizarme mejor con el lenguaje de programación Dart.

**Comment by laamebaespaical64** [comment]
El día 28 de agosto, instalé Flutter, el SDK de Dart y Visual Studio Code. Luego, añadí los SDK de Dart y Flutter a las variables de entorno del sistema. Con esto, configuré mi entorno de desarrollo en Visual Studio Code utilizando el código predeterminado que ofrece Flutter. Realicé pruebas tanto en un emulador de teléfono Android en Android Studio como en la web, y además, creé un sencillo programa de calculadora siguiendo tutoriales en YouTube para familiarizarme con el lenguaje de programación Dart.
El día jueves 5 de septiembre subí los archivos al repositorio, listo para empezar a trabajarlo.
