### ISSUE TITLE
1.1	Diseñar la Interfaz de Registro e Inicio de Sesión

### ISSUE THREAD

**Issue by laamebaespaical64** [ISCOUTB/DH-VocesdelAula#4]
Crear un mockup de las pantallas de registro e inicio de sesión, asegurando que sean intuitivas y fáciles de usar.

**Comment by laamebaespaical64** [comment]
Empecé con el desarrollo de la interfaz de la pantalla de inicio a partir del diseño echo![Image](https://github.com/user-attachments/assets/5f762579-369b-4402-9a49-9e2039ce53b2)

**Comment by laamebaespaical64** [comment]
Le falta todavía pero avancé con la pantalla de inicio

![Image](https://github.com/user-attachments/assets/60eddcc3-8223-4bd2-a01d-fb5d3c60ef74)

**Comment by laamebaespaical64** [comment]
Terminé la pantalla de inicio y la de login, solo les faltaría pulir algunos detalles para que se vean mejor

Pantalla de inicio:
![Image](https://github.com/user-attachments/assets/40db9cf5-dd15-4880-a8a2-ef010fbe0b67)

Login:
![Image](https://github.com/user-attachments/assets/40f772cc-70c3-48ff-8d48-cacfddaeb5e9)

**Comment by laamebaespaical64** [comment]
Empecé todo desde cero, esta vez trabajando con screens  y rutas, la pantalla de inicio quedó lista, solo habría que cambiar una imagen, las screens de login y register están en proceso.

Pantalla de inicio:
![Image](https://github.com/user-attachments/assets/0ce35559-e90b-4d1d-bf80-3bc19318e709)

**Comment by laamebaespaical64** [comment]
Terminé con las interfaces de login y register, a las cuales se puede acceder desde la pantalla principal a través de sus respectivos botones.

Login:
![Image](https://github.com/user-attachments/assets/3ffd963a-7b00-4c5d-9f03-b878b6758a14)


Register:
![Image](https://github.com/user-attachments/assets/659c049a-4a8a-43e5-bc47-80ecb001a978)

**Comment by jairoserrano** [comment]
adelante
