### ISSUE TITLE
2.1	Diseñar la Interfaz de Evaluación de Profesores

### ISSUE THREAD

**Issue by laamebaespaical64** [ISCOUTB/DH-VocesdelAula#9]
Crear un mockup de la pantalla donde los estudiantes puedan calificar y comentar sobre los profesores.

**Comment by leogoca00** [comment]
![Image](https://github.com/user-attachments/assets/d38c51a6-7689-41aa-a5b0-78a63c9cb53e)
Este es el diseño prototipo de la interfaz de evaluacion de profesores, para el proximo adelanto se agregaran los colores de la UTB y mas adelantos

**Comment by laamebaespaical64** [comment]
Se hizo la pantalla de evaluación de profesores
![Image](https://github.com/user-attachments/assets/f3770e49-8242-4baf-a8ce-9874a30c8ff4)
